"""Reading the figures out of a notice annexure.

A GST notice does not argue in prose, it argues in tables. Every limb carries a
head-wise row — SGST, CGST, IGST, Cess and a total — and the whole reply hangs
off those five numbers. Getting them into the matter is therefore not a
convenience; a reply that restates the department's figures wrongly is worse
than one that does not restate them at all.

WHY NOT A TABLE-EXTRACTION LIBRARY
----------------------------------
PDF table extraction is a guess dressed up as a parse. These notices are
generated by departmental software into layouts that collapse unpredictably:
a header row printed across three lines, values wrapping under their own
labels, whole columns interleaved. A library returns a grid either way and
gives no signal about whether the grid is right.

So this module uses the property the numbers themselves supply. A head-wise
row is four component amounts followed by their own total, and

    sgst + cgst + igst + cess == total

That arithmetic is a checksum the document carries for free. A run of five
numbers that satisfies it is a real head-wise row to a near certainty; a run
that does not is discarded. Nothing that fails its own arithmetic reaches the
matter, and every figure that does is marked unconfirmed until a human agrees
with it.
"""

import re
from typing import Any, Dict, List, Optional

# A bare integer or decimal, possibly with Indian digit grouping.
#
# The leading lookbehind excludes a digit run that is part of a hyphenated
# identifier — the "1" of GSTR-1, the "10" of ASMT-10, the "01" of DRC-01.
# Those are not money and they are everywhere in the prose of a notice. Left
# in, they enter the sliding window below as though they were head amounts:
# on a real limb reading "...declared in GSTR-1 ... reported in GSTR-1 ...
# IGST 0.00 CGST 42,150.00 ...", the two stray 1s and the following two
# figures summed to within the rounding tolerance of the wrong total, passed
# the checksum, and reported Rs. 42,152 for a limb the annexure put at
# Rs. 84,300.
NUMBER_RE = re.compile(
    r"(?<![\w.])(?<![A-Za-z]-)"
    r"(\d{1,3}(?:,\d{2,3})*(?:\.\d{1,2})?|\d+(?:\.\d{1,2})?)(?![\w])"
)

# A head-wise row is printed as a row. Its five figures sit within a line or
# two of each other, never with a paragraph of prose between them.
#
# This is the structural guard behind the checksum, and it is what makes the
# checksum trustworthy: four arbitrary numbers scattered through prose will
# occasionally sum to a fifth, and the tolerance that exists for paisa drift
# is exactly wide enough to let a coincidence through. Requiring the run to be
# contiguous removes the coincidence rather than tightening the arithmetic,
# which would reject genuine rounded rows.
MAX_ROW_SPAN = 140

# Column orders seen in departmental annexures. The Tamil Nadu scrutiny
# attachment prints SGST first; central formats usually print CGST first.
DEFAULT_HEAD_ORDER = ("sgst", "cgst", "igst", "cess")

HEAD_ORDER_RE = re.compile(
    r"\b(SGST|CGST|IGST|CESS)\b", re.IGNORECASE,
)

# Labels that mark the row a reply actually has to answer, as opposed to the
# working rows above it.
OPERATIVE_LABELS = (
    "difference", "excess", "short", "total ineligible", "net", "payable",
    "recoverable", "demand",
)

# Rounding slack, in rupees. Departmental annexures round components to whole
# rupees and occasionally carry a paisa of drift into the total.
TOLERANCE = 2.0


def _to_float(raw: str) -> Optional[float]:
    try:
        return float(raw.replace(",", ""))
    except (TypeError, ValueError, AttributeError):
        return None


def detect_head_order(text: str) -> List[str]:
    """
    Read the column order off the annexure header where it is legible.

    Falls back to the Tamil Nadu order rather than guessing per-row, because a
    guess that varies row to row produces a matter whose heads do not add up
    across defects.
    """
    seen: List[str] = []
    for match in HEAD_ORDER_RE.finditer(text or ""):
        head = match.group(1).lower()
        if head not in seen:
            seen.append(head)
        if len(seen) == 4:
            break
    if len(seen) == 4 and set(seen) == set(DEFAULT_HEAD_ORDER):
        return seen
    return list(DEFAULT_HEAD_ORDER)


def find_head_rows(text: str, head_order: Optional[List[str]] = None) -> List[Dict[str, Any]]:
    """
    Every head-wise row in the text whose components sum to its own total.

    Returns rows in document order, each carrying the label that preceded it so
    a caller can tell a working row from the operative one.
    """
    if not text:
        return []
    order = head_order or detect_head_order(text)

    tokens = [
        (match.start(), match.end(), _to_float(match.group(1)))
        for match in NUMBER_RE.finditer(text)
    ]
    tokens = [t for t in tokens if t[2] is not None]

    rows: List[Dict[str, Any]] = []
    used_until = -1

    for start_index in range(len(tokens) - 4):
        window = tokens[start_index:start_index + 5]
        if window[0][0] < used_until:
            continue
        components = [value for _, _, value in window[:4]]
        total = window[4][2]

        # The five figures must have been printed as one row. Without this the
        # checksum can be satisfied by coincidence across a paragraph of prose.
        if window[4][1] - window[0][0] > MAX_ROW_SPAN:
            continue

        # The checksum. Also require a non-trivial total, or every run of
        # zeroes in the document qualifies.
        if total <= 0 or abs(sum(components) - total) > TOLERANCE:
            continue
        # A row of all-equal tiny numbers is a column header ("1 2 3 4 10"),
        # not a money row.
        if total < 10:
            continue

        amounts = {order[i]: components[i] for i in range(4)}
        rows.append({
            "label": _label_before(text, window[0][0]),
            "amounts": {k: v for k, v in amounts.items() if v},
            "total": round(total, 2),
            "position": window[0][0],
            "head_order": list(order),
        })
        used_until = window[4][1]

    return rows


def _label_before(text: str, position: int, window: int = 160) -> str:
    """The words immediately preceding a numeric run — its row label."""
    fragment = text[max(0, position - window):position]
    fragment = re.sub(r"\s+", " ", fragment).strip()
    # Drop leading serial numbers and column rulers.
    fragment = re.sub(r"^[\d\s|]+", "", fragment)
    return fragment[-120:].strip()


def operative_row(text: str, head_order: Optional[List[str]] = None) -> Optional[Dict[str, Any]]:
    """
    The single row a defect turns on.

    Departmental annexures build to their conclusion: several working rows and
    then a difference or excess. The last row whose label reads as operative is
    that conclusion; where no label qualifies, the largest total is taken and
    marked so the reviewer knows it was chosen rather than read.
    """
    rows = find_head_rows(text, head_order)
    if not rows:
        return None

    operative = [
        row for row in rows
        if any(label in (row["label"] or "").lower() for label in OPERATIVE_LABELS)
    ]
    if operative:
        chosen = operative[-1]
        chosen = dict(chosen, basis="labelled")
        return chosen

    chosen = max(rows, key=lambda r: r["total"])
    return dict(chosen, basis="largest")


# ---------------------------------------------------------------------------
# Fallbacks for rows the checksum cannot reach
# ---------------------------------------------------------------------------

# "1 2 1150 1150" — a late-fee row: a count, then two equal head amounts with
# no printed total. Common enough to be worth naming.
#
# The trailing lookahead is not decoration. Without it the leading
# `\d{1,3}` alternative matches the first three digits of "1150" and reports
# "115", and the backreference then never fires on any four-digit figure —
# which is most of them.
PAIRED_HEADS_RE = re.compile(
    r"(?<![\w.])(\d{1,3}(?:,\d{2,3})+(?:\.\d{1,2})?|\d+(?:\.\d{1,2})?)(?![\w.])"
    r"\s+\1(?![\w.])"
)

# "5 Difference (Highest of 1 to 3)-4 481548" — a single unallocated figure.
#
# The gap between the word and the figure carries digits of its own (row
# numbers, table references, "1 to 3"), so this cannot be matched by excluding
# digits. The line is located first and the largest number ON THAT LINE is
# taken, which is the reported difference in every departmental layout seen:
# the working references are small and the amount is not.
DIFFERENCE_LINE_RE = re.compile(
    r"^.*\b(?:difference|excess|short\s*payment|shortfall|total)\b.*$",
    re.IGNORECASE | re.MULTILINE,
)

# "penalty ... of Rs. 25000/- each under CGST and SGST" — a per-head penalty
# stated once. Read literally it understates the exposure by half.
EACH_HEAD_RE = re.compile(
    r"(?:Rs\.?|INR|₹)\s*(\d{1,3}(?:,\d{2,3})*(?:\.\d{1,2})?|\d+)\s*/?-?\s*"
    r"each\s+under\s+(?:the\s+)?([A-Z/ ]{4,20}?)\s+and\s+([A-Z/ ]{4,20}?)\b",
    re.IGNORECASE,
)

_HEAD_WORDS = {"cgst": "cgst", "sgst": "sgst", "igst": "igst",
               "utgst": "sgst", "tngst": "sgst", "cess": "cess"}


def each_head_penalty(text: str) -> Optional[Dict[str, Any]]:
    """A penalty expressed as one figure levied under each of two heads."""
    match = EACH_HEAD_RE.search(text or "")
    if not match:
        return None
    value = _to_float(match.group(1))
    if not value:
        return None
    heads = []
    for raw in (match.group(2), match.group(3)):
        key = _HEAD_WORDS.get(re.sub(r"[^a-z]", "", raw.lower()))
        if key and key not in heads:
            heads.append(key)
    if len(heads) != 2:
        return None
    return {
        "label": _label_before(text, match.start()),
        "amounts": {heads[0]: value, heads[1]: value},
        "total": round(value * 2, 2),
        "position": match.start(),
        "head_order": [],
        "basis": "each-head",
    }


def paired_head_row(text: str, head_order: Optional[List[str]] = None) -> Optional[Dict[str, Any]]:
    """
    A CGST/SGST pair printed without a total, as late-fee rows are.

    Every match is examined rather than only the first: departmental tables are
    full of "0 0" runs, and stopping at the first pair found reports nothing on
    a table that does carry a real figure further down.
    """
    order = head_order or detect_head_order(text)
    intra = [h for h in order if h in ("sgst", "cgst")]
    if len(intra) != 2:
        return None

    for match in PAIRED_HEADS_RE.finditer(text or ""):
        value = _to_float(match.group(1))
        if not value:
            continue
        return {
            "label": _label_before(text, match.start()),
            "amounts": {intra[0]: value, intra[1]: value},
            "total": round(value * 2, 2),
            "position": match.start(),
            "head_order": list(order),
            "basis": "paired",
        }
    return None


def single_difference(text: str) -> Optional[Dict[str, Any]]:
    """An unallocated difference figure, as turnover limbs print."""
    best: Optional[Dict[str, Any]] = None
    for line_match in DIFFERENCE_LINE_RE.finditer(text or ""):
        line = line_match.group(0)
        values = [
            (_to_float(m.group(1)), m.start())
            for m in NUMBER_RE.finditer(line)
        ]
        values = [(v, p) for v, p in values if v and v >= 100]
        if not values:
            continue
        value, offset = max(values, key=lambda pair: pair[0])
        candidate = {
            "label": re.sub(r"\s+", " ", line).strip()[:120],
            "amounts": {"unallocated": value},
            "total": round(value, 2),
            "position": line_match.start() + offset,
            "head_order": [],
            "basis": "unallocated",
        }
        # Later lines supersede earlier ones: departmental tables build to
        # their difference row, they do not open with it.
        best = candidate
    return best


def read_defect_amount(
    text: str,
    head_order: Optional[List[str]] = None,
    fallback_text: str = "",
) -> Optional[Dict[str, Any]]:
    """
    Best available reading of what a defect alleges, in descending confidence.

    `fallback_text` is searched only when the defect's own text yields nothing.
    It exists because departmental PDFs do not reliably emit in reading order,
    and the first limb's table is sometimes extracted above its own heading.

    Returns None rather than a guess when nothing can be read. An empty amount
    a reviewer can see and fill is safe; a wrong one they cannot see is not.
    """
    for source in (text, fallback_text):
        if not source:
            continue
        for reader in (
            lambda s=source: operative_row(s, head_order),
            lambda s=source: paired_head_row(s, head_order),
            lambda s=source: each_head_penalty(s),
            lambda s=source: single_difference(s),
        ):
            row = reader()
            if row:
                return row
    return None


def summarise(rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Aggregate head-wise rows, for the matter-level total."""
    totals: Dict[str, float] = {}
    for row in rows:
        for head, amount in (row.get("amounts") or {}).items():
            totals[head] = round(totals.get(head, 0.0) + float(amount or 0), 2)
    return {
        "by_head": totals,
        "total": round(sum(totals.values()), 2),
        "row_count": len(rows),
    }
